name: a_living_dictionary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  smooth_page_indicator: ^1.0.0+2

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.3
  image_picker: ^0.8.6
  firebase_storage: ^11.0.5
  file_picker: ^5.2.2
  provider: ^6.0.4
  kakao_flutter_sdk_user: ^1.2.2
  firebase_auth: ^4.1.3
  flutterfire_ui: ^0.4.3+20

  flutter_webview_plugin: ^0.4.0
  flutter_web_auth: ^0.5.0
  uuid: ^3.0.7
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  flutter_provider: ^2.1.0
  flutter_google_places: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen.png
  android_12: