// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTIyRY4bMe1PNuOCarsQa7hnN0Q5nBZI',
    appId: '1:574173650365:web:23e80ddd90032f03b446d4',
    messagingSenderId: '574173650365',
    projectId: 'a-living-dictionary',
    authDomain: 'a-living-dictionary.firebaseapp.com',
    storageBucket: 'a-living-dictionary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmFEe4Z8ZsTWA3Q-ovkmtK-8rJJabGUz8',
    appId: '1:574173650365:android:98fd6098038ee4feb446d4',
    messagingSenderId: '574173650365',
    projectId: 'a-living-dictionary',
    storageBucket: 'a-living-dictionary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9AAcxEawTGBaeB8c_pNDySBTEcW8yG_w',
    appId: '1:574173650365:ios:b3cebb3ca8ed9fb6b446d4',
    messagingSenderId: '574173650365',
    projectId: 'a-living-dictionary',
    storageBucket: 'a-living-dictionary.appspot.com',
    iosClientId: '574173650365-khlfq6iv3hs443m6h3de7jd6lbq0pop4.apps.googleusercontent.com',
    iosBundleId: 'kr.ac.kumoh.teammobile.aLivingDictionary',
  );
}
